### ISSUE TITLE
希望能加入多种提醒方式

### ISSUE THREAD

**Issue by zdian** [subjadeites/ffxiv-gatherer-clock#2]
比如任务栏闪烁，或者简单提示音，或者弹窗。
办公室上班偷偷尼 不方便听声音

**Comment by subjadeites** [comment]
目前TODO里有一个置顶窗口的计划，在摸了在摸了

**Comment by subjadeites** [comment]
> 比如任务栏闪烁，或者简单提示音，或者弹窗。 办公室上班偷偷尼 不方便听声音

悬浮窗已加入 @zdian 
https://github.com/subjadeites/ffxiv-gatherer-clock/releases/tag/1.4.2 

简单提示音TODO

**Comment by subjadeites** [comment]
已经加入提示音和悬浮窗两种提示方式，有新的想法可以再开issue~
